depth_multiple: 0.33  # model depth multiple
width_multiple: 0.375  # layer channel multiple

backbone:
  # [from, number, module, args]
  [[-1, 1, RepVGGBlock, [64, 3, 2]],  # 0-P1/2
   [-1, 1, RepVGGBlock, [128, 3, 2]],  # 1-P2/4
   [-1, 6, RepBlock, [128]],
   [-1, 1, RepVGGBlock, [256, 3, 2]],  # 3-P3/8
   [-1, 12, RepBlock, [256]],
   [-1, 1, RepVGGBlock, [512, 3, 2]],  # 5-P4/16
   [-1, 18, RepBlock, [512]],
   [-1, 1, RepVGGBlock, [1024, 3, 2]],  # 7-P5/32
   [-1, 6, RepBlock, [1024]],
   [-1, 1, SimSPPF, [1024, 5]]]  # 9

neck:
  [
    [ 6, 1,ConvBNAct,[ 512, 3, 2 ] ],
    [ [ -1, 9 ], 1, Concat, [ 1 ] ],
    [ -1, 1, GiraffeNeckV2, [ 1024, 1.0 ] ],  #512+1024 merge_3  12

    [ -1, 1, nn.Upsample, [ None, 2, 'nearest' ] ],
    [ 4, 1,ConvBNAct,[ 256, 3, 2 ] ],
    [ [ -1, 6, 13 ], 1, Concat, [ 1 ] ],
    [ -1, 1, GiraffeNeckV2, [ 512, 1.0 ] ], #256+512+1024 merge_4 16

    [ -1, 1, nn.Upsample, [ None, 2, 'nearest' ] ],
    [ [ -1, 4 ], 1, Concat, [ 1 ] ],
    [ -1, 1, GiraffeNeckV2, [ 128, 1.0 ] ], # 512+256  merge_5  19  out

    [ -1, 1,ConvBNAct,[ 256, 3, 2 ] ],
    [ [ -1, 16 ], 1, Concat, [ 1 ] ],
    [ -1, 1, GiraffeNeckV2, [ 256, 1.0 ] ], # 512+256  merge_7  22  out

    [ 16, 1,ConvBNAct,[ 512, 3, 2 ] ],
    [ -2, 1,ConvBNAct,[ 512, 3, 2 ] ],
    [ [ -1, 12,-2 ], 1, Concat, [ 1 ] ],
    [ -1, 1, GiraffeNeckV2, [ 512, 1.0 ] ], # 512+512+1024 merge_6 26  out
  ]  # 23 (P5/32-large)

effidehead:
  [[19, 1, Head_layers, [128,0,8]], #if use_dfl is False, please set reg_max to 0
  [22, 1, Head_layers, [256,0,8]],
  [26, 1, Head_layers, [512,0,8]],
  [[27,28,29],1,Out,[]]]




