depth_multiple: 1.0  # model depth multiple
width_multiple: 1.0  # layer channel multiple

# yolov7 net Simplified version, same as yolov7 official version
backbone:
  # [from, number, module, args]
  [[-1, 1, Conv, [32, 3, 1]],  # 0
   [-1, 1, Conv, [64, 3, 2]],  # 1-P1/2
   [-1, 1, Conv, [64, 3, 1]],
   [-1, 1, Conv, [128, 3, 2]],  # 3-P2/4
   [-1, 1, ELAN, [128, 256]],   #cin 128  cout 256
   [-1, 1, MP1, [256]],
   [-1, 1, ELAN, [256, 512]],   #cin 256  cout 512   #####6
   [-1, 1, MP1, [512]],
   [-1, 1, ELAN, [512, 1024]],   #####8
   [-1, 1, MP1, [1024]],
   [-1, 1, ELAN, [1024, 1024]],   ######10
  ]

# yolov7 head
head:
  [[-1, 1, SPPCSPC, [512]], # 11
   [-1, 1, Conv, [256, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [8, 1, Conv, [256, 1, 1]], # route backbone P4
   [[-1, -2], 1, Concat, [1]],

   [-1, 1, ELAN_H, [512, 256]],  #16

   [-1, 1, Conv, [128, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [6, 1, Conv, [128, 1, 1]], # route backbone P3  #19
   [[-1, -2], 1, Concat, [1]],

  [-1, 1, ELAN_H, [256, 128]],  #21
   [-1, 1, MP, []],
   [-1, 1, Conv, [128, 1, 1]],
   [-3, 1, Conv, [128, 1, 1]],
   [-1, 1, Conv, [128, 3, 2]],
   [[-1, -3, 16], 1, Concat, [1]],

   [-1, 1, ELAN_H, [512, 256]],  #27
   [-1, 1, MP, []],
   [-1, 1, Conv, [256, 1, 1]],
   [-3, 1, Conv, [256, 1, 1]],
   [-1, 1, Conv, [256, 3, 2]],
   [[-1, -3, 11], 1, Concat, [1]],
   
   [-1, 1, ELAN_H, [1024, 512]],  #33
   [19, 1, RepVGGBlock, [256, 3, 1]],
   [27, 1, RepVGGBlock, [512, 3, 1]],
   [33, 1, RepVGGBlock, [1024, 3, 1]],
   [[34,35,36], 1, IDetect, [nc, anchors]],   # Detect(P3, P4, P5)
  ]
