depth_multiple: 1.0  # model depth multiple
width_multiple: 1.0  # layer channel multiple
backbone:  # MAE-TinyNAS_res for small
  # [from, number, module, args]
  [
  [-1, 1, Focus, [3, 32, 3, 1, relu]],
  [-1, 1, SuperResStem, [128, 24, 3, 2, 1]],
  [-1, 1, SuperResStem, [128, 88, 3, 2, 5]],  #out 2
  [-1, 1, SuperResStem, [256, 128, 3, 2, 3]],
  [-1, 1, SuperResStem, [256, 120, 3, 1, 2]],  #out 4
  [-1, 1, SuperResStem, [512, 144, 3, 2, 1, True]], # 5
  ]

neck:
  [
    [ 4, 1,ConvBNAct,[ 256, 3, 2 ] ],
    [ [ -1, 5 ], 1, Concat, [ 1 ] ], # 768
    [ -1, 1, GiraffeNeckV2, [ 512, 1.0, 0.75 ] ],  #  12

    [ -1, 1, nn.Upsample, [ None, 2, 'nearest' ] ],
    [ 2, 1,ConvBNAct,[ 128, 3, 2 ] ],
    [ [ -1, 4, 9 ], 1, Concat, [ 1 ] ], # 896
    [ -1, 1, GiraffeNeckV2, [ 256, 1.0, 0.75] ], # merge_4 12

    [ -1, 1, nn.Upsample, [ None, 2, 'nearest' ] ],
    [ [ -1, 2 ], 1, Concat, [ 1 ] ], # 384
    [ -1, 1, GiraffeNeckV2, [ 128, 1.0, 0.75 ] ], # 512+256  merge_5  15  out

    [ -1, 1,ConvBNAct,[ 128, 3, 2 ] ],
    [ [ -1, 12 ], 1, Concat, [ 1 ] ], # 384
    [ -1, 1, GiraffeNeckV2, [ 256, 1.0, 0.75 ] ], # 512+256  merge_7  18  out

    [ 12, 1,ConvBNAct,[ 256, 3, 2 ] ],
    [ -2, 1,ConvBNAct,[ 256, 3, 2 ] ],
    [ [ -1, 8,-2 ], 1, Concat, [ 1 ] ], # 1024
    [ -1, 1, GiraffeNeckV2, [ 512, 1.0, 0.75 ] ], # 512+512+1024 merge_6 22  out
  ]  # 23 (P5/32-large)

effidehead:
  [[15, 1, Head_out, [128, 0]],
  [18, 1, Head_out, [256, 0]],
  [22, 1, Head_out, [512, 0]],
  [[23, 24, 25], 1, Out, []]]


