depth_multiple: 1.0  # model depth multiple
width_multiple: 1.0  # layer channel multiple
backbone:  # MAE-TinyNAS_csp for med
  # [from, number, module, args]
  [
  [-1, 1, Focus, [3, 32, 3, 1, silu]],
  [-1, 1, TinyNAS_CSP, [128, 64, 2, 3, 2]],
  [-1, 1, TinyNAS_CSP, [128, 64, 2, 3, 4]],  #out 2
  [-1, 1, TinyNAS_CSP_2, [128, 256, 256, 2, 3, 4,  256, 256, 256, 1, 3, 4]],
  [-1, 1, TinyNAS_CSP, [512, 256, 2, 3, 3, True]], # 4
  ]

neck:
  [
    [ 3, 1,ConvBNAct,[ 256, 3, 2 ] ],
    [ [ -1, 4 ], 1, Concat, [ 1 ] ], # 768
    [ -1, 1, GiraffeNeckV2, [ 512, 1.5, 1.0 ] ],  #  8

    [ -1, 1, nn.Upsample, [ None, 2, 'nearest' ] ],
    [ 2, 1,ConvBNAct,[ 128, 3, 2 ] ],
    [ [ -1, 3, 8 ], 1, Concat, [ 1 ] ], # 896
    [ -1, 1, GiraffeNeckV2, [ 256, 1.5, 1.0] ], # merge_4 12

    [ -1, 1, nn.Upsample, [ None, 2, 'nearest' ] ],
    [ [ -1, 2 ], 1, Concat, [ 1 ] ], # 384
    [ -1, 1, GiraffeNeckV2, [ 128, 1.5, 1.0 ] ], # 512+256  merge_5  15  out

    [ -1, 1,ConvBNAct,[ 128, 3, 2 ] ],
    [ [ -1, 11 ], 1, Concat, [ 1 ] ], # 384
    [ -1, 1, GiraffeNeckV2, [ 256, 1.5, 1.0 ] ], # 512+256  merge_7  18  out

    [ 11, 1,ConvBNAct,[ 256, 3, 2 ] ],
    [ -2, 1,ConvBNAct,[ 256, 3, 2 ] ],
    [ [ -1, 7, -2 ], 1, Concat, [ 1 ] ], # 1024
    [ -1, 1, GiraffeNeckV2, [ 512, 1.5, 1.0 ] ], # 512+512+1024 merge_6 22  out
  ]  # 23 (P5/32-large)

effidehead:
  [[14, 1, Head_out, [128, 0]],
  [17, 1, Head_out, [256, 0]],
  [21, 1, Head_out, [512, 0]],
  [[22, 23, 24], 1, Out, []]]


