depth_multiple: 1.0  # model depth multiple
width_multiple: 1.0  # layer channel multiple
backbone:
  # [from, number, module, args]
  [[-1, 1, ConvWrapper, [64, 3, 2]],  # 0-P1/2
   [-1, 1, ConvWrapper, [128, 3, 2]],  # 1-P2/4
   [-1, 1, BepC3, [128, 6, "ConvWrapper"]],
   [-1, 1, ConvWrapper, [256, 3, 2]],  # 3-P3/8
   [-1, 1, BepC3, [256, 12, "ConvWrapper"]],
   [-1, 1, ConvWrapper, [512, 3, 2]],  # 5-P4/16
   [-1, 1, BepC3, [512, 18, "ConvWrapper"]],
   [-1, 1, ConvWrapper, [1024, 3, 2]],  # 7-P5/32
   [-1, 1, BepC3, [1024, 6, "ConvWrapper"]],
   [-1, 1, SPPF, [1024, 5]]]  # 9
neck:
   [
    [ 6, 1,ConvBNAct,[ 256, 3, 2, silu ] ],
    [ [ -1, 9 ], 1, Concat, [ 1 ] ], # 768
    [ -1, 1, GiraffeNeckV2, [ 512, 1.5, 1.0, silu ] ],  #  8

    [ -1, 1, nn.Upsample, [ None, 2, 'nearest' ] ],
    [ 4, 1,ConvBNAct,[ 128, 3, 2, silu ] ],
    [ [ -1, 6, 13 ], 1, Concat, [ 1 ] ], # 896
    [ -1, 1, GiraffeNeckV2, [ 256, 1.5, 1.0, silu ] ], # merge_4 12

    [ -1, 1, nn.Upsample, [ None, 2, 'nearest' ] ],
    [ [ -1, 4 ], 1, Concat, [ 1 ] ], # 384
    [ -1, 1, GiraffeNeckV2, [ 128, 1.5, 1.0, silu ] ], # 512+256  merge_5  15  out

    [ -1, 1,ConvBNAct,[ 128, 3, 2, silu ] ],
    [ [ -1, 16 ], 1, Concat, [ 1 ] ], # 384
    [ -1, 1, GiraffeNeckV2, [ 256, 1.5, 1.0, silu ] ], # 512+256  merge_7  18  out

    [ 16, 1,ConvBNAct,[ 256, 3, 2, silu ] ],
    [ -2, 1,ConvBNAct,[ 256, 3, 2, silu ] ],
    [ [ -1, 12, -2 ], 1, Concat, [ 1 ] ], # 1024
    [ -1, 1, GiraffeNeckV2, [ 512, 1.5, 1.0, silu ] ], # 512+512+1024 merge_6 22  out
   ]

effidehead:
  [[19, 1,Head_out , [128, 16]],
  [22, 1, Head_out, [256, 16]],
  [26, 1, Head_out, [512, 16]],
  [[27, 28, 29], 1, Out, []]]


