depth_multiple: 0.33  # model depth multiple
width_multiple: 0.375  # layer channel multiple

# RepGhostBottleneck [48, 3, 1, 192, 480, 0.5, 0]
# in_channel, k, s, c, exp_size, width, se_ratio
# out_channel = _make_divisible(c * width, 4)
# mid_channel = _make_divisible(exp_size * width, 4)
# _make_divisible: It ensures that all layers have a channel number that is divisible by 4 ?
# exp: c = 24, exp_size = 36, width = 0.5
# out_channel = _make_divisible(12,4) = 4, mid_channel = _make_divisible(36 * 0.5, 4) = 20
# arg[0]: in channel, arg[3],arg[5]:out channel, arg[4],arg[5]:mid_channel (mid_channel is define by yourself)

backbone:   # RepGhostNet 1.0× width = 1
  # [from, number, module, args]
  [
    [-1, 1, ConvBnAct, [16, 3, 2]], # Normal Conv with ReLU activation /2
    #stage1
    [-1, 1, RepGhostBottleneck, [16, 3, 1, 16, 8, 1, 0]],
    #stage2
    [-1, 1, RepGhostBottleneck, [16, 3, 2, 24, 24, 1, 0]],  # /4
    [-1, 1, RepGhostBottleneck, [24, 3, 1, 24, 36, 1, 0]],
    #stage3
    [-1, 1, RepGhostBottleneck, [24, 5, 2, 40, 36, 1, 0.25]], # /8
    [-1, 1, RepGhostBottleneck, [40, 5, 1, 40, 60, 1, 0.25]], # 5
    # stage4
    [-1, 1, RepGhostBottleneck, [40, 3, 2, 80, 120, 1, 0]], # /16
    [-1, 1, RepGhostBottleneck, [80, 3, 1, 80, 100, 1, 0]],
    [-1, 1, RepGhostBottleneck, [80, 3, 1, 80, 120, 1, 0]],
    [-1, 1, RepGhostBottleneck, [80, 3, 1, 80, 120, 1, 0]],
    [-1, 1, RepGhostBottleneck, [80, 3, 1, 112, 240, 1, 0.25]],
    [-1, 1, RepGhostBottleneck, [112, 3, 1, 112, 336, 1, 0.25]], #11
     # stage5
    [-1, 1, RepGhostBottleneck, [112, 5, 2, 160, 336, 1, 0.25]], # /32
    [-1, 1, RepGhostBottleneck, [160, 5, 1, 160, 480, 1, 0]],
    [-1, 1, RepGhostBottleneck, [160, 5, 1, 160, 480, 1, 0.25]],
    [-1, 1, RepGhostBottleneck, [160, 5, 1, 160, 480, 1, 0]],
    [-1, 1, RepGhostBottleneck, [160, 5, 1, 160, 480, 1, 0.25]],

    [-1, 1, SimSPPF, [960, 5]],  # 9
  ]

neck: # YOLOv6T neck
  [[-1, 1, SimConv, [256, 1, 1]],#18
   [-1, 1, Transpose, [256]],
   [[-1, 11], 1, Concat, [1]],
   [-1, 12, RepBlock, [256]],

   [-1, 1, SimConv, [128, 1, 1]],#22
   [-1, 1, Transpose, [128]],
   [[-1, 5], 1, Concat, [1]],
   [-1, 12, RepBlock, [128]],   #out 25

   [-1, 1, SimConv, [128, 3, 2]],
   [[-1, 22], 1, Concat, [1]],  # cat head P4
   [-1, 12, RepBlock, [256]],  # 28 (P4/16-medium)

   [-1, 1, SimConv, [256, 3, 2]],
   [[-1, 18], 1, Concat, [1]],  # cat head P5
   [-1, 12, RepBlock, [512]]]  # 31 (P5/32-large)

effidehead:
  [[25, 1, Head_layers, [128, 0]],
  [28, 1, Head_layers, [256, 0]],
  [31, 1, Head_layers, [512, 0]],
  [[32, 33, 34], 1, Out, []]]
#backbone:   # RepGhostNet 1.0× width = 1
#  # [from, number, module, args]
#  [
#    [-1, 1, ConvBnAct, [16, 3, 2]], # Normal Conv with ReLU activation /2
#    #stage1
#    [-1, 1, RepGhostBottleneck, [16, 3, 1, 16, 8, 1, 0]],
#    #stage2
#    [-1, 1, RepGhostBottleneck, [16, 3, 2, 24, 24, 1, 0]],  # /4
#    [-1, 1, RepGhostBottleneck, [24, 3, 1, 24, 36, 1, 0]],
#    #stage3
#    [-1, 1, RepGhostBottleneck, [24, 5, 2, 40, 36, 1, 0.25]], # /8
#    [-1, 1, RepGhostBottleneck, [40, 5, 1, 40, 60, 1, 0.25]], # 5
#    # stage4
#    [-1, 1, RepGhostBottleneck, [40, 3, 2, 80, 120, 1, 0]], # /16
#    [-1, 1, RepGhostBottleneck, [80, 3, 1, 80, 100, 1, 0]],
#    [-1, 1, RepGhostBottleneck, [80, 3, 1, 80, 120, 1, 0]],
#    [-1, 1, RepGhostBottleneck, [80, 3, 1, 80, 120, 1, 0]],
#    [-1, 1, RepGhostBottleneck, [80, 3, 1, 112, 240, 1, 0.25]],
#    [-1, 1, RepGhostBottleneck, [112, 3, 1, 112, 336, 1, 0.25]], #11
#     # stage5
#    [-1, 1, RepGhostBottleneck, [112, 5, 2, 160, 336, 1, 0.25]], # /32
#    [-1, 1, RepGhostBottleneck, [160, 5, 1, 160, 480, 1, 0]],
#    [-1, 1, RepGhostBottleneck, [160, 5, 1, 160, 480, 1, 0.25]],
#    [-1, 1, RepGhostBottleneck, [160, 5, 1, 160, 480, 1, 0]],
#    [-1, 1, RepGhostBottleneck, [160, 5, 1, 160, 480, 1, 0.25]],
#
#    [-1, 1, ConvBnAct, [960, 1, 1]], # Normal Conv with ReLU activation 160 to 960
#  ]
#
#neck: # YOLOv6T neck
#  [[-1, 1, SimConv, [256, 1, 1]],#18
#   [-1, 1, Transpose, [256]],
#   [[-1, 11], 1, Concat, [1]],
#   [-1, 12, RepBlock, [256]],
#
#   [-1, 1, SimConv, [128, 1, 1]],#22
#   [-1, 1, Transpose, [128]],
#   [[-1, 5], 1, Concat, [1]],
#   [-1, 12, RepBlock, [128]],   #out 25
#
#   [-1, 1, SimConv, [128, 3, 2]],
#   [[-1, 22], 1, Concat, [1]],  # cat head P4
#   [-1, 12, RepBlock, [256]],  # 28 (P4/16-medium)
#
#   [-1, 1, SimConv, [256, 3, 2]],
#   [[-1, 18], 1, Concat, [1]],  # cat head P5
#   [-1, 12, RepBlock, [512]]]  # 31 (P5/32-large)
#
#effidehead:
#  [[25, 1, Head_layers, [128, 0]],
#  [28, 1, Head_layers, [256, 0]],
#  [31, 1, Head_layers, [512, 0]],
#  [[32, 33, 34], 1, Out, []]]




